[package]
name = "keygen"
version.workspace = true
edition = "2024"
authors.workspace = true
license.workspace = true

[[bin]]
name = "keygen"
path = "src/main.rs"

[dependencies]
rsa = { workspace = true }
rand = { workspace = true }
